### ISSUE TITLE
Getting Nil Response

### ISSUE THREAD

**Issue by abhisheksmartdata** [Medable/iOS-SDK#3]
As guided i successfully integrated sdks through cocoa pods and i created one App in Medable.I am getting successful response when using Postman But getting Nil response every time for every object(MDFault,MDAccount,etc.).I am not also getting that where to pass the URL if required.Kindly please help in rectifying the issue.
Thanks

**Comment by billybiset** [comment]
Hi @abhisheksmartdata, a few things could cause this. The most common one when you are starting your setup would be that your Environments.plist file doesn't have the necessary Org data.

Here is an example entry in that file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Medable-Client-Key</key>
	<string>SOME_CLIENT_KEY</string>
	<key>org</key>
	<string>YOUR_ORG_NAME</string>
	<key>Protocol</key>
	<string>https</string>
	<key>BASEURL</key>
	<string>medable.com</string>
	<key>APIPrefix</key>
	<string>dev</string>
</dict>
</plist>
```

*Warning*: It must be listed under a key matching your configuration (e.g. ```Debug```) and you must use your own org name and client key.

Of course, other things could be causing this. If you can provide more info we can certainly help you out. Thanks for reaching out to us.

**Comment by billybiset** [comment]
Also, the Sample Apps have an [example file](https://github.com/Medable/iOS-SDK/blob/master/Sample%20Apps/MedableTest/MedableTest/Resources/Environments.plist) for this

**Comment by abhisheksmartdata** [comment]
Hi Billy,

Thanks for your suggestion,As u suggested here and also by following the sampleApp i implemented the same but i still getting Nil response for callback parameters for all object requests.What else can be the issue in getting Nil response as i made similar Environment Plist and calling the same method as in view controller.m file and also try to call authenticateSessionWithEmail Method.with login credentials "abhishekb@smartdatainc.net/Abhi$hek25" and passing empty or nil token and SingleUse True value.But not getting any error or fault in response but gets Nil for each callback object.

**Comment by mirlhaq** [comment]
Hi @abhisheksmartdata, I'm Fer, I can help too. Could you please paste your code here and also if you happen to have what's on your console?

**Comment by abhisheksmartdata** [comment]
Thanks @mirlhaq ,For your help.I am attaching screenshots of my code.
![Uploading environment.png…]()
![Uploading infoPlist.png…]()
![Uploading signInMethod.png…]()

**Comment by mirlhaq** [comment]
@abhisheksmartdata I think the uploading process of your screenshots didn't finish because the ticket was closed before. Could you solve the issue?

**Comment by abhisheksmartdata** [comment]
@mirlhaq Sorry for inconvenience,that was due to bad internet connection.
Environment.Plist
<key>Debug</key>
	<dict>
		<key>Medable-Client-Key</key>
		<string>nFKOoLCZC1rbyw47Q7Ypwy</string>
		<key>org</key>
		<string>smartdataapp</string>
		<key>Protocol</key>
		<string>https</string>
		<key>BASEURL</key>
		<string>dev.medable.com</string>
		<key>APIPrefix</key>
		<string>api</string>
	</dict>
/////////////////////////////////////////////////////
Calling Method for SignIn

    [[MDAPIClient sharedClient]
     authenticateSessionWithEmail:@"abhishekb@smartdatainc.net"
     password:@"Abhi$hek25"
     verificationToken:nil    // or @"" for 1st time Login to get kNewLocation
     singleUse:YES
     callback:^(MDAccount *localUser, MDFault *fault)
     {
         if (!fault && localUser)
         {
             
         }
         else
         {
             if (fault)
             {
                 if ([fault.code isEqual:kMDAPIErrorNewLocation] ||
                     [fault.code isEqual:kMDAPIErrorUnverifiedLocation])
                 {
                     // Device verification handling
                 }
                 else
                 {
                     // Other faults handling
                 }
             }
             else
             {
                 // Login failed without MDFault (i.e. time out, etc)
             }
         }
     }];
/////////////////////////////////////////////////
Info.Plist

<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>Configuration</key>
	<string>Debug</string>
	<key>CFBundleIdentifier</key>
	<string>Abhishek.$(PRODUCT_NAME:rfc1034identifier)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
</dict>

**Comment by mirlhaq** [comment]
Check in you project's plist file if you added a *$(CONFIGURATION)* entry.

For more detailed info, check this repo's Readme.md under the *Add an entry in the Info.plist file* title.

All the rest seems OK.

Let me know how it goes!

**Comment by abhisheksmartdata** [comment]
@mirlhaq earlier the value in Configuration key was Debug and now i changed to as suggested $(CONFIGURATION).But the result is the same,Nil.When i manually try to hit web service it bring up the response but not with SDK.I noticed one more thing while Xcode Debug Navigator is that when i do it manually then their is the network connection which shows 5kb/s but when i do it with SDK it shows zero kb/s.

**Comment by mirlhaq** [comment]
Hi @abhisheksmartdata I got your project source, and added that "Configuration : ${CONFIGURATION}" pair the project's *Info.plist* file and ran it on the simulator, the login worked on the first try.

However I'll try some other things... I can't get to repro the kNewLocation loop issue.

I'm sending the plist file to your email.

**Comment by mirlhaq** [comment]
Ok, checked everything on a real device using your credentials. Everything works fine, even the whole flow: kNewLocation / kUnverifiedLocation / verification token / successful authentication.

I'll send you the whole working project by email. I've put some comments in your authentication method in ViewController.

Closing this now.
