### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by izotx** [Medable/iOS-SDK#5]
I found couple inconsistencies in the documentation.

1.In  https://github.com/Medable/iOS-SDK/blob/master/Documentation/manualInstall.md the link to download the latest framework is broken.

2 ... Add a linker flag (-ObjC), this allows you to use class extensions provided by our framework.

Didn't work for me and project was crashing on start. I replaced it with the following values copied from the sample app: 

$(inherited) -ObjC -l"ObjC" -framework "CFNetwork" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreText" -framework "ImageIO" -framework "Medable" -framework "MobileCoreServices" -framework "QuartzCore" -framework "SystemConfiguration"

**Comment by billybiset** [comment]
@izotx What was the crash on startup?

Thanks for the heads up, I made a few small changes to this document.

**Comment by izotx** [comment]
It was complaining about external types. As of today I can't replicate the error though.

**Comment by billybiset** [comment]
Ok
